services:
  bookshelf:
    build: .
    container_name: shelf_book
    ports:
      - "50080:80"
    volumes:
      - ./db:/db
      - ./cache:/cache
      - ./books:/books:ro
    environment:
      - TZ=UTC
      - PAGE_SIZE=20
      - COVER_SIZE=300
      - COVER_QUALITY=70
    restart: unless-stopped
